journey
    title Experience Map : Road-trip romain (Lyon -> Toulouse)
    section Planification
      Consulte son GPS classique (trajet direct 5h15): 3
      Se dit "Quel gâchis, il doit y avoir des sites romains": 1
      Saisit Lyon-Toulouse, Antiquité, Détour max +25%: 3
    section Itinéraire personnalisé
      Découvre un trajet via Minerve (6h30): 5
      Suit l'itinéraire: 6
    section Partage
      Envoie l'itinéraire final à un collègue: 7
