# Utiliser une image Python comme base
FROM python:3.11-slim

COPY requirements.txt /app/requirements.txt

WORKDIR /app

# Installer le client PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client && apt-get clean

RUN pip install -r requirements.txt

# Remplissage de la table category
CMD ["python", "-m", "db_fill.categories_fill"]
