{
 "title": "Contenu BDD Datatourisme",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Monitoring Contenu BDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Régions en BDD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM region" }
   ]
  },
  {
   "title": "Départements en BDD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM departement"
    }
   ]
  },
  {
   "title": "Villes en BDD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM city " }
   ]
  },
  {
   "title": "Category POI en BDD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM category " }
   ]
  },
  {
   "title": "POI en BDD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM point_of_interest "
    }
   ]
  },
  { "title": "Monitoring Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Airflow Service",
   "type": "stat",
   "description": "Monitoring du service Airflow",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_up{job=\"airflow\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Service",
   "type": "stat",
   "description": "Monitoring du service PostgreSQL",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Datatourisme / Taille BDD sur Disque",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"datatourisme\"}",
     "legendFormat": "Taille BDD en MB"
    }
   ]
  },
  {
   "title": "Redis Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Public API Service",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"http://api:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Datatourisme ETL V2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_run_state{dag=\"datatourisme_etl_v2\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}