services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql_docker/data
      - ./init/init.sh:/docker-entrypoint-initdb.d/000-init.sh
      - ./init/database_create.sql:/docker-entrypoint-initdb.d/sql/000-database_create.sql

volumes:
  postgres_data: